### ISSUE TITLE
Unity2022でのAvatarCopyUtilityのウィンドウの不具合

### ISSUE THREAD

**Issue by amehuri** [whiteflare/AvatarTools#1]
VCC2.2.2にてUnity2022に移行したプロジェクトで、AvatarCopyUtilityのウィンドウに各コンポーネントのあるオブジェクトの一覧が表示されないようです。
コピー自体は動作しています。

![image](https://github.com/whiteflare/AvatarTools/assets/110208161/0fbfab0c-2818-4101-b1d3-d13a3605d5e3)

**Comment by whiteflare** [comment]
報告ありがとうございます。そして発見が遅れてしまい申し訳ありません。
Unity2022で一部プロパティフィールドが動作しなかった件は下記コミットで修正されております。
https://github.com/whiteflare/AvatarTools/commit/aaa1f308b48ec6d46fe3b44087681c2dfa537f81
よろしくお願いします。
